apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-fine-1
spec:
  parallelism: 2
  template:
    metadata:
      name: job-wq-fine-1
    spec:
      containers:
        - name: c
          image: docker.io/jebla/job-wq-1
          env:
            - name: BROKER_URL
              value: amqp://guest:guest@rabbitmq-service:5672
            - name: QUEUE
              value: job1
      restartPolicy: OnFailure
